### ISSUE TITLE
make eco2 + tvoc properties to match sensor standard

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_SGP30#1]
https://github.com/adafruit/Adafruit_CircuitPython_SGP30/commit/ed1db09ff8b6ac2625a9bace2fe9ce5aca034846#commitcomment-25187627

**Comment by sommersoft** [comment]
To clarify, change all property instances of `tvoc` to `TVOC`, and `eco2` to `eCO2`. 

Outlined in the design guide [here](https://github.com/adafruit/circuitpython/blob/master/docs/design_guide.rst#sensor-properties-and-units).

Like so:
```python
# old
@property
    def tvoc(self):
```
```python
# new
@property
    def TVOC(self):
```

**Comment by ladyada** [comment]
yep thats it - super easy :D but have to update examples, readme too!

**Comment by process1183** [comment]
I'd be happy to work on this one!

**Comment by ladyada** [comment]
@process1183 go for it!
