### ISSUE TITLE
Error in sensor data?

### ISSUE THREAD

**Issue by djmbritt** [adafruit/Adafruit_CircuitPython_SGP30#16]
So I managed to set up the sensor. But I keep getting values around 400 for eCO2 and 0 for TVOC. 
Do I need to burn the sensor in?
Does it take a while before it starts outputting true values?
It does change when I blow on it. So it does seem to be working properly.
I just get the feeling it's not outputting real world values.

**Comment by ladyada** [comment]
yes it takes a while until it outputs true values. also it needs calibration!
https://learn.adafruit.com/adafruit-sgp30-gas-tvoc-eco2-mox-sensor/arduino-code#baseline-set-and-get-4-20

**Comment by djmbritt** [comment]
Ha! I should've known better and properly read the docs 😅
Thanks for the quick reply it's working properly now. 
I do have another question tho.

Do I need to input the values provided by get_iaq_baseline() in to set_iaq_baseline() periodically?
Or does the iaq_init() method update the baseline values automatically for me?

**Comment by ladyada** [comment]
you have to DIY!

**Comment by djmbritt** [comment]
Thanks for the quick reply :+1:

**Comment by benkelaci** [comment]
So, basically do I need to get the baseline values with this command: get_iaq_baseline(), then set hourly back the current values with set_iaq_baseline() ?

And the first time the sensor needs to run for 12 hours to get the correct baseline values, right? Sorry but the "Baseline Set & Get" section is not clear for me.

If you can illustrate with a small (but complete) code snippet, that would be the best. Thank you for your help.
