### ISSUE TITLE
Incorrect feature set value for newer chips

### ISSUE THREAD

**Issue by chrisbartley** [adafruit/Adafruit_CircuitPython_SGP30#19]
The _SGP30_FEATURESET const is set to 0x0020:

https://github.com/adafruit/Adafruit_CircuitPython_SGP30/blob/master/adafruit_sgp30.py#L54

...but in newer versions of the SGP30, the value should be 0x0022.  See https://www.tmsnet.eu/assets/pdf/pdfsrc.php?MPN=SGP30-2.5K&T=25__530

**Comment by ladyada** [comment]
it happens :) wanna submit a PR that will check either value (or a masked' value?)

**Comment by chrisbartley** [comment]
Yep thanks, sure thing, working on it :-)

**Comment by ladyada** [comment]
hiya any updates?

**Comment by chrisbartley** [comment]
Yes, sorry, was on vacation, and then covered up by the catching up after vacation :-\ Will submit a new PR early this week.

**Comment by ladyada** [comment]
all good! just checkin' in :)

**Comment by chrisbartley** [comment]
OK, committed.  Apologies for my taking so long to fix a single line of code!

**Comment by ladyada** [comment]
all good - you did great! :)
