### ISSUE TITLE
RuntimeError: SGP30 Not detected

### ISSUE THREAD

**Issue by davidschoefberger** [adafruit/Adafruit_CircuitPython_SGP30#21]
Hi,
I just got a Adafruit SGP30 sensor breakout. Unfortunately, the sensor is not working. The output is the following:

```
File "30test", line 11, in <module>
sgp30 = adafruit_sgp30.Adafruit_SGP30(i2c)
File "/home/pi/sgp30.py", line 69, in __init__
raise RuntimeError('SGP30 Not detected')
RuntimeError: SGP30 Not detected
```

When I unplug the sensor afterwards and plug it back in, I can find the sensor with `i2cdetect -y 1`. After the next try to read the values, the sensor disappears.

There is another report in the Adafruit forum: https://forums.adafruit.com/viewtopic.php?f=19&t=158492

Do you have an idea how to solve it?

Thanks,
David

**Comment by kattni** [comment]
This has been resolved in the new release of this library. You can download the latest version from this GitHub repo, or wait approximately 24 hours for it to be included in the bundle.

**Comment by Sameep147** [comment]
I am trying to use sgp30 but everytime it is showing sensor not detected . Somebody please help me

**Comment by tannewt** [comment]
@Sameep147 please post to the Adafruit Tech support forum: https://forums.adafruit.com/
