### ISSUE TITLE
Irq baseline issue

### ISSUE THREAD

**Issue by yifanff** [adafruit/Adafruit_CircuitPython_SGP30#22]
Hi , the irq baseline hard code as following in the example code. 
sgp30.set_iaq_baseline(0x8973, 0x8aae)
In the Pi3 board i got the 400ppm value with eCO2 output all the time. The root cause is the baseline should be updated, right? How could i get the right baseline value? thanks.

**Comment by ladyada** [comment]
https://learn.adafruit.com/adafruit-sgp30-gas-tvoc-eco2-mox-sensor/arduino-code#baseline-set-and-get-4-20

**Comment by yifanff** [comment]
Thanks for sharing!
