### ISSUE TITLE
simpletest.py set_iaq_relative_humidity parameter is celsius

### ISSUE THREAD

**Issue by borch84** [adafruit/Adafruit_CircuitPython_SGP30#38]
Hello, in the simpletest.py the celcius parameter is misspelled and it should be celsius:

sgp30.set_iaq_relative_humidity(celsius=22.1, relative_humidity=44)

Thanks.

**Comment by pandianmn** [comment]
created a PR - https://github.com/adafruit/Adafruit_CircuitPython_SGP30/pull/39

**Comment by caternuson** [comment]
Should be fixed with #39. Thanks!
